"""baseline

Revision ID: f287d18c4a3f
Revises: 
Create Date: 2026-04-20 18:45:54.875118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f287d18c4a3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('careers_url', sa.String(length=512), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('company_tier', sa.String(length=32), nullable=True),
    sa.Column('tier_source', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_normalized_name'), ['normalized_name'], unique=True)

    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_summary_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_runs_status'), ['status'], unique=False)

    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('preset', sa.String(length=64), nullable=True),
    sa.Column('profile_yaml', sa.Text(), nullable=True),
    sa.Column('profile_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_is_active'), ['is_active'], unique=False)

    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('query_json', sa.JSON(), nullable=True),
    sa.Column('cadence_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_h1b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('filings_count', sa.Integer(), nullable=False),
    sa.Column('approvals_count', sa.Integer(), nullable=False),
    sa.Column('denials_count', sa.Integer(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', name='uq_company_h1b_year')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_job_id', sa.String(length=255), nullable=True),
    sa.Column('canonical_url', sa.String(length=1024), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('normalized_title', sa.String(length=512), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name_raw', sa.String(length=255), nullable=True),
    sa.Column('location_raw', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('remote_type', sa.String(length=32), nullable=True),
    sa.Column('employment_type', sa.String(length=32), nullable=True),
    sa.Column('level_guess', sa.String(length=32), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('recruiter_blob_json', sa.JSON(), nullable=True),
    sa.Column('source_metadata_json', sa.JSON(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_job_id', name='uq_job_source_extid')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_external_job_id'), ['external_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_normalized_title'), ['normalized_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_url_hash'), ['url_hash'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('next_action_at', sa.DateTime(), nullable=True),
    sa.Column('resume_version', sa.String(length=64), nullable=True),
    sa.Column('cover_letter_version', sa.String(length=64), nullable=True),
    sa.Column('portal_url', sa.String(length=1024), nullable=True),
    sa.Column('notes_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_status', sa.String(length=32), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_job_id'), ['job_id'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_payload_json', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_events_watch_id'), ['watch_id'], unique=False)

    op.create_table('job_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('reason_json', sa.JSON(), nullable=True),
    sa.Column('ranking_version', sa.String(length=32), nullable=False),
    sa.Column('ranked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'profile_id', name='uq_ranking_job_profile')
    )
    with op.batch_alter_table('job_rankings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_rankings_composite_score'), ['composite_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_rankings_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_rankings_profile_id'), ['profile_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_job_id'), ['job_id'], unique=False)

    op.create_table('screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('prefilter_passed', sa.Boolean(), nullable=False),
    sa.Column('prefilter_reasons_json', sa.JSON(), nullable=True),
    sa.Column('llm_status', sa.String(length=32), nullable=False),
    sa.Column('llm_model_name', sa.String(length=128), nullable=True),
    sa.Column('screening_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'profile_id', name='uq_screening_job_profile')
    )
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenings_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenings_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenings_profile_id'))
        batch_op.drop_index(batch_op.f('ix_screenings_job_id'))

    op.drop_table('screenings')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_job_id'))
        batch_op.drop_index(batch_op.f('ix_notes_company_id'))

    op.drop_table('notes')
    with op.batch_alter_table('job_rankings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_rankings_profile_id'))
        batch_op.drop_index(batch_op.f('ix_job_rankings_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_rankings_composite_score'))

    op.drop_table('job_rankings')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_watch_id'))
        batch_op.drop_index(batch_op.f('ix_job_events_job_id'))

    op.drop_table('job_events')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_job_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_company_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))

    op.drop_table('applications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_url_hash'))
        batch_op.drop_index(batch_op.f('ix_jobs_source'))
        batch_op.drop_index(batch_op.f('ix_jobs_posted_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_normalized_title'))
        batch_op.drop_index(batch_op.f('ix_jobs_is_active'))
        batch_op.drop_index(batch_op.f('ix_jobs_external_job_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_jobs_company_id'))

    op.drop_table('jobs')
    op.drop_table('company_h1b')
    op.drop_table('watches')
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_is_active'))

    op.drop_table('user_profile')
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_runs_status'))

    op.drop_table('scrape_runs')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_normalized_name'))

    op.drop_table('companies')
    # ### end Alembic commands ###
